openapi: 3.0.1
info:
  title: Product API
  description: Pactflow Product API demo
  version: 1.0.0
paths:
  /products:
    get:
      summary: List all products
      description: Returns all products
      operationId: getAllProducts
      responses:
        '200':
          description: successful operation
          content:
            application/vnd.api+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
              examples:
                Example:
                  value:
                    - data:
                        id: '321'
                        type: product
                        attributes:
                          version: '2'
                          price: 47.11
        '400':
          description: Invalid ID supplied
          content: {}
components:
  schemas:
    Product:
      type: object
      x-examples:
        Example:
          data:
            id: '321'
            type: product
            attributes:
              version: '2'
              price: 47.11
      properties:
        data:
          type: object
          properties:
            id:
              type: string
              example: '321'
            type:
              type: string
              enum:
                - product
              example: product
            attributes:
              type: object
              required:
                - price
              properties:
                version:
                  type: string
                  example: '2'
                price:
                  type: number
                  example: 47.11
                  minimum: 0
                  exclusiveMinimum: false
          required:
            - id
            - type
            - attributes
